version: '3.7'

services:
    postgres:
        image: 'postgres:11.1-alpine'
        ports: ['5432:5432']
        environment:
            - POSTGRES_DB=event-store
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - TZ=Europe/Berlin
    app:
        build:
            context: .
        ports: ['3000:3000']
        environment:
            - POSTGRES_DB=postgres://user:password@localhost:5432/event-store